{% set name = "pytest-cloud" %}
{% set version = "5.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e52a27d2d3666af79a1c44d49c6c98297aec4af5b713c0ccbc807788e7b8e227

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - psutil
    - pytest >=3.6.1
    - pytest-xdist >=1.26.0
    - python >=3.4
    - setuptools
    - six
    - timeout-decorator >=0.3.2
    - virtualenv

test:
  imports:
    - pytest_cloud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pytest-cloud
  summary: Distributed tests planner plugin for pytest testing framework.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marcelotrevisani
