{% set name = "pytest-cloud" %}
{% set version = "5.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 717bb1680d3b98bc7bfc90ba5913d46fc157d06321dfe50d7de8aa3977f5ff87

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - psutil
    - pytest >=3.6.1
    - pytest-xdist >=1.26.0
    - python
    - setuptools
    - six
    - timeout-decorator >=0.3.2

test:
  imports:
    - pytest_cloud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pytest-cloud
  summary: Distributed tests planner plugin for pytest testing framework.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marcelotrevisani
